name: Tests

on:
  push:
    branches:
      - master

  pull_request_target:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20-bullseye
      ports:
        - 12700:12700
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
