name: Tests

on:
  push:
    branches:
      - master

  pull_request_target:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make tests
